Exploration of the file ALLdata.csv

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
df1 = pd.read_csv('fulltimeNY.csv')

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   position     986 non-null    object
 1   company      986 non-null    object
 2   description  986 non-null    object
 3   numreview    755 non-null    object
 4   location     986 non-null    object
dtypes: object(5)
memory usage: 38.6+ KB

There are 5 variables in this dataset. According to 'type', all of them are strings, but the numreview variable is a numerical variables which is read as an object because the entries contain the word "reviews". Since we are not interested in this variable, we are not going yo change it.

There are no null values in any of the variables, except for numreview, which again is not of interest for us, so we are not gonna clean them.

In [5]:
df1.head(30)

,position,company,description,numreview,location
0,Data Scientistâ€”Research (Ref # EXEC/RD_DAT_NYC...,New York State Office of the Attorney General ...,"<span id=""job_summary"" class=""summary""><p><b>E...",NaN,"New York, NY"
1,Data Scientist/Pre Sales Engineer,Celonis,"<span id=""job_summary"" class=""summary""><p>Celo...",NaN,"New York, NY"
2,Data Analyst/Research Scientist,Columbia University Medical Center,"<span id=""job_summary"" class=""summary""><p>We a...",217 reviews,"New York, NY 10032"
3,Data Scientist,fractalanalytics,"<span id=""job_summary"" class=""summary""><div><p...",NaN,"Jersey City, NJ"
4,Data Scientist,Blackboard Insurance,"<span id=""job_summary"" class=""summary""><div><p...",NaN,"New York, NY"
5,Data Analyst / Data Scientist,Defined Clarity,"<span id=""job_summary"" class=""summary""><div><p...",NaN,"New York, NY"
6,Staff Data Scientist,Foursquare,"<span id=""job_summary"" class=""summary""><b>Abou...",7 reviews,"New York, NY"
7,Clinical Data Assistant - IPC,NYU Langone Health,"<span id=""job_summary"" class=""summary"">NYU Lan...",705 reviews,"New York, NY 10016"
8,Data Analytics Specialist,DEPARTMENT OF CITY PLANNING,"<span id=""job_summary"" class=""summary"">THE AGE...",NaN,"Manhattan, NY"
9,"Data Scientist, Supply Chain Analytics",HelloFresh,"<span id=""job_summary"" class=""summary"">Come se...",208 reviews,"New York, NY"
10,"Data Scientist, Analytics",Freshly,"<span id=""job_summary"" class=""summary""><div><d...",7 reviews,"New York, NY"
11,Statistical Analyst/Data Scientist (Machine Le...,Medidata Solutions,"<span id=""job_summary"" class=""summary""><div><d...",33 reviews,"New York, NY 10003"
12,Data Visualization Data Scientist,Capital One,"<span id=""job_summary"" class=""summary""><div>11...","6,318 reviews","New York, NY 10261"
13,Data Scientist,Prudential,"<span id=""job_summary"" class=""summary""><div><d...","2,010 reviews","Newark, NJ"
14,Data Scientist (Data Science Team),OppenheimerFunds,"<span id=""job_summary"" class=""summary""><div>Jo...",40 reviews,"New York, NY"
15,Data Scientist,"J.Crew Group, Inc.","<span id=""job_summary"" class=""summary""><b>Titl...",760 reviews,"New York, NY 10003"
16,Quantitative Analyst Developer,Axioma Inc.,"<span id=""job_summary"" class=""summary""><div><h...",NaN,"New York, NY"
17,Image Processing Scientist,"Topcon Medical Systems, Inc.","<span id=""job_summary"" class=""summary""><div><d...",NaN,"Oakland, NJ"
18,Sales Engineer,Gro Intelligence,"<span id=""job_summary"" class=""summary""><b>Abou...",NaN,"New York, NY 10001"
19,"Senior Evaluation Coordinator, New York City T...",DEPT OF HEALTH/MENTAL HYGIENE,"<span id=""job_summary"" class=""summary"">The Cen...",8 reviews,"Bronx, NY"
20,"Director, Data Science",Capital One,"<span id=""job_summary"" class=""summary""><div>11...","6,318 reviews","New York, NY 10261"
21,Clinical Trial Research Analyst,Memorial Sloan Kettering,"<span id=""job_summary"" class=""summary""><div><d...",703 reviews,"New York, NY"
22,Data Scientist,Sweeten,"<span id=""job_summary"" class=""summary""><div><p...",NaN,"New York, NY"
23,Data Scientist,"Edison Software, Inc.","<span id=""job_summary"" class=""summary"">The Rol...",NaN,"New York, NY"
24,Senior Quantitative Analyst,TD Securities,"<span id=""job_summary"" class=""summary""><div><d...",108 reviews,"New York, NY 10019"
25,"Senior Associate, Data Scientist/Statistics --...",KPMG,"<span id=""job_summary"" class=""summary""><div><p...","4,491 reviews","New York, NY 10154"
26,Data Scientist,Organic,"<span id=""job_summary"" class=""summary""><div><p...",32 reviews,"New York, NY"
27,Senior Research Analyst,New York University,"<span id=""job_summary"" class=""summary""><div><h...",699 reviews,"New York, NY"
28,Grants Manager - LOH,NYU Langone Health,"<span id=""job_summary"" class=""summary"">NYU Lan...",705 reviews,"New York, NY 10003"
29,Jr Data Scientist,CalliÃ¨re Group,"<span id=""job_summary"" class=""summary""><div>We...",NaN,"New York, NY"

In [6]:
df1.describe()

,position,company,description,numreview,location
count,986,986,986,755,986
unique,731,501,977,190,115
top,Data Scientist,NYU Langone Health,"<span id=""job_summary"" class=""summary""><div><p...",705 reviews,"New York, NY"
freq,103,77,2,76,503

In [7]:
# Check for duplicates
df1.duplicated().sum()

0

There are not duplicates. 
The names of the variables are already standardizes, so the data cleaning is finished and we proceed to the EDA.

What type of positions are most required?
We will look into data analyst, data scientist and data engineer. In addition, we will check junior and senior positions.

In [8]:
#check the unique entries of the position
df1['position'].unique()

array(['Data Scientistâ€”Research (Ref # EXEC/RD_DAT_NYC_6073)',
       'Data Scientist/Pre Sales Engineer',
       'Data Analyst/Research Scientist', 'Data Scientist',
       'Data Analyst / Data Scientist', 'Staff Data Scientist',
       'Clinical Data Assistant - IPC', 'Data Analytics Specialist',
       'Data Scientist, Supply Chain Analytics',
       'Data Scientist, Analytics',
       'Statistical Analyst/Data Scientist (Machine Learning)',
       'Data Visualization Data Scientist',
       'Data Scientist (Data Science Team)',
       'Quantitative Analyst Developer', 'Image Processing Scientist',
       'Sales Engineer',
       'Senior Evaluation Coordinator, New York City Teens Connection, Bronx Neighborhood Health Action Center',
       'Director, Data Science', 'Clinical Trial Research Analyst',
       'Senior Quantitative Analyst',
       'Senior Associate, Data Scientist/Statistics -- Financial Services',
       'Senior Research Analyst', 'Grants Manager - LOH',
       'Jr Data Scientist', 'Machine Learning Data Scientist',
       'Game Data Scientist', 'Data Scientist - Analytics',
       'Junior Data Scientist', 'Jr. Data Scientist', 'Data Scientist I',
       'Applied Data Scientist', 'Customer Data Scientist',
       'Data & Applied Scientist',
       'Data Scientist, Content Business Analysis',
       'Data Scientist, Modeling Team', 'Data Scientist II',
       'Research Data Scientist', 'Data Scientist (NYC)',
       'Data Scientist, Customer Operations',
       'Data Scientist, Machine Learning & AI',
       'Policy Analyst (Data Scientist)', 'PMC: Data Scientist',
       'Product Data Scientist', 'Data Scientist - AVP',
       'Data Scientist, Markets Research',
       'Risk Analyst / Data Scientist',
       'Data Intelligence - Research & Development Scientist',
       'Software Developer / Data Scientist',
       'Customer Facing Data Scientist',
       'Data Scientist - Journey Analytics',
       'Machine / Learning Data Scientist', 'Lead Data Scientist',
       'Data Scientist - Bomoda',
       'People Research Scientist, People Analytics',
       'Data Scientist/Quantitative Analyst Intern, Summer 2018',
       'Data Scientist and Machine Learning Researcher',
       'Data Scientist (Product)', 'Applied Scientist',
       'Data Scientist, Premium Analytics', 'Data Scientist- Ads',
       'DATA SCIENTIST',
       'Consumer Finance - Decision and Data Scientist - Analyst/Associate - New York City',
       'Experienced Data Scientist',
       'NYL Post Grad Internship: Data Scientist/Statistician',
       'Bioinformatics Scientist / Data Scientist',
       'Genomic Data Scientist',
       'Data Science - Data Scientist - New York', 'Image Data Scientist',
       'Applied Scientist, Catalog Item Relationships',
       'Behavioral Scientist', 'Business/Data Analysis',
       'Data Scientist - Private Bank', 'Sr Data Scientist',
       'Data Scientist - Portfolio Management Strategy and Analytics-New York, NY',
       'Data Scientist / Sr Strategic Analyst', 'Data Scientist/Engineer',
       'Senior Data Scientist', 'Data Scientist - Investment Bank',
       'Data Scientist with Credit Risk Experience',
       'Assistant Research Scientist', 'Research Data Associate',
       'Personal Financial Management - Decision and Data Scientist - Associate/Vice President- New York City',
       'Data Analyst', 'Associate Data Scientist', 'Field Data Scientist',
       'Applied Data Scientist in Infrastructure',
       'Applied Scientist- AI', 'Data Scientist - Marketing',
       'Data Scientist, Group Benefits and Middle Market P&C',
       'AI Scientist - New York',
       'GIR, Data Strategy, Analyst/Associate - New York',
       'Data Scientist Analyst JG18', 'Clinical Data Scientist',
       'Research Position (Various Levels), Systems Biology',
       'Quantitative Corporate Finance Analyst',
       'Associate Director, Data & Analysis',
       'Associate Scientist II, Synthesis', 'Associate, Client Success',
       'Senior Software Engineer - Data', 'Senior Grants Specialist',
       'Sales Strategy Associate', 'Assistant Administrator',
       'Statistical Programmer Analyst', 'Tech Lead',
       'Director, Financial Services - Data Scientist',
       'Predictive Modeling Analyst',
       'Junior Account Manager (E-commerce Focus)', 'Director of Data',
       'Computer Vision & Machine Learning Engineer',
       'Senior Data Engineer', 'Machine Learning Infrastructure Engineer',
       'Bell Labs -Data Analytics and Machine Learning',
       'Quantitative Research Analyst', 'Assistant Registrar',
       'Mgr/Sr Mgr-Model Risk Management - Data Scientist',
       'Manager, Business & Data Analysis - Business Intelligence',
       'Market Research Analyst',
       'Azure Data Scientist, Senior Associate',
       'IoT Intern (Computer Science/Electrical Engineering)',
       'Software Engineer (Python, Data Platform)', 'Research Technician',
       'Research Assistant', 'Head of Creator Marketplace Intelligence',
       'GSAM, Fixed Income, Distressed Research Analyst - Vice President',
       'Global Research Summer Analyst Program 2019',
       'VP - Machine Learning Engineer - Center of Excellence',
       'Medical Communications Specialist, Bureau of Public Health Training',
       'Bioinformatics Engineer - New York', 'Big Data SW Engineer',
       'Lead Analyst-Solutions Development',
       'Specialist - Healthcare Analytics & Delivery, New Ventures',
       'Research Engineer, AI (University Grad)',
       'Research Associate - In Vivo Pharmacology',
       'Sr. Research Analyst', 'Junior Statistical Programmer',
       'Data Engineer', 'Senior Data Science Engineer',
       'Sr. Financial Analyst', 'Environmental Scientist II',
       'Research Scientist/Senior Research Scientist',
       'Equity Research Analyst (Biotech)',
       'Technical Support Specialist, Biotech',
       'Compliance Officer - Healthcare Analytics, New Ventures',
       'Commodity Markets Research Analyst',
       'Field Technician-Environmental Compliance',
       'Neuroscience Research Specialist',
       'Data Quality/CDE Analysis Lead',
       'Equity Research - REITs Analyst/Associate',
       'Financial Project Analyst (Real Estate Development and Facilities)',
       'VP, Business Intelligence', 'Bioinformatics Scientist',
       'Associate Director, Data Science (2018030)',
       'Translational Core Administrator', 'QA Engineer',
       'FGP Senior Billing Rep (35)', 'Equity Manager Research Analyst',
       'Quantitative Analyst', 'Software Engineer, Machine Learning',
       'Manager, Data Scientist (ML/NLP) -- Financial Services',
       'Analytics Expert - Journey Analytics, New Ventures',
       'CIB Data Analytics â€“ Program Execution Associate',
       'Senior Manager Data Scientist',
       'Manager of Analytics - Data Scientist',
       'Instagram - Software Engineer, Machine Learning',
       'Decision Scientist - Associate - CIB Treasury Services',
       'Environmental Scientist/Geologist/Engineer',
       'Deputy Director for Child Welfare Reporting',
       'Azure Data Scientist, Manager',
       'Lead Data Science Instructor, Principal Data Scientist',
       'Quantitative Analyst - Equity Derivatives',
       'Junior Research and Development Analyst',
       'Quality Control Scientist', 'Environmental Scientist',
       'Electron Microscopy Technician', 'Cyber Analyst',
       'Contract, Accounts Payable Associate (New York)',
       'Data Engineering Manager, Analytics (Instagram)',
       'Global Manager, Data Integration',
       'Fixed Income Research Analyst',
       'Electroneurodiagnostic Technologist II-BV',
       'Sr Operations Analyst', 'Facility Budget Research Analyst',
       'Serve Jersey City - Community Research Analyst',
       'Machine Learning Engineer', 'Financial Controller',
       'Technical Recruiter', 'Analyst, Data Analytics',
       'Quantitative Analyst, High Frequency Trading',
       'Principal Researcher',
       'Analyst - Healthcare Analytics & Delivery, McKinsey New Ventures',
       'Regulatory/Financial Analyst (Associate) - Data & Statistics - Research and Statistics Group',
       'Python Developer', 'Assistant Director, Admissions',
       'Data Science Manager - Life Sciences Industry',
       'Derivative Quant Trader, Delta One Group',
       'Data Scientist, Engineering', 'Technical Writer',
       'Quantitative Research Analyst Gaming and Digital Entertainment',
       'Director Data Science', 'Associate - Machine Learning',
       'Data Science Manager', 'Quantitative Equity Risk Analyst',
       'Supervisor-Echocardiography Svcs',
       'Cyber Analytics Data Scientist, Manager',
       'Statistical Programmer', 'Electroneurodiagnostic Techg II - BV',
       'Data Analytics Platform Developer',
       'Data Analytics Platform GUI Developer', 'Energy Program Analyst',
       'Research Analyst', 'IPSC Process Development Associate',
       'Value Analyst', 'Product Manager',
       'Machine Learning Engineer - Center of Excellence - Associate',
       'UX Researcher', 'Accounts Receivable Associate(New York)',
       'Molecular Technologist',
       'Data Scientist Lead - Global Research & Data Analytics - ED',
       'Data Scientist & Engineer', 'Director, Member Data Science',
       'Solutions Analyst', 'HR Manager', 'Genetics Counselor',
       'Business Development Associate', 'Equity Research Analyst/ REITs',
       'Scientist, Analytical Sciences',
       'Quantitative Analyst - Model Validation Group',
       'Research Technician I', 'Clinical Research Associate II',
       'Principal Data Science', 'HRIS Coordinator/Specialist',
       'Data Linkage Operations and Research Manager, Bureau of Epidemiology Services',
       'Assessment Science Partner, People Analytics',
       'Business Analyst - Science', 'Research & Quality Manager',
       'BI Developer', 'Data Analysis Manager', 'Producer',
       'Senior Associate - Cognitive Data Scientist Natural Language Processing',
       'Senior Scientist, Content Science',
       'Special Assistant to the Deputy Commissioner/CHE',
       'Continuous Improvement Manager',
       'Software Engineer / Research Scientist - Question Answering',
       'Vice President, DFIR', 'CIB - Data Science Data Engineer - VP',
       'Senior Research Scientist (Domestic)',
       'Global Quantitative Analytics Analyst Program - 2019',
       'Manager, Investment Data', 'Retail Solutions Consultant',
       'Lead Data Engineer',
       'Revenue Management Analyst-Process Improvement',
       'Citi Research â€“ Research Product Analyst, AVP (NY)',
       'Sr. Data Engineer',
       'Chief Technology Officer - McKinsey Academy, New Ventures',
       'Data Science Lead, Editorial Lab', 'Research Assistants',
       'Bioanalytical Scientist', 'Global Insights for Adjacencies',
       'Sales Engineer, Machine Learning, Google Cloud',
       'Analyst, Research Finance',
       'Managing Applications Consultant - Supply Chain Business / Functional Data Scientist',
       'Pathology Lab Accessioner',
       'Lead Researcher-BCG Turn Transformation/ BCG Henderson Institute',
       'Real Estate Research Analyst', 'Growth Hacker (AI Games)',
       'Associate Director, Senior Data Scientist', 'Associate Scientist',
       'Exciting Senior Data Scientist at Successful Startup',
       'Research Study Specialist- Immunotherapy Core service',
       'Business Analyst', 'Assistant Research Technician â€“ Cardiology',
       'Associate, Analytics',
       'Global Lead, Ecommerce Strategy and Capabilities',
       'Head, Americas Machine Learning and AI Specialist Solutions Architecture',
       'Quantitative Researcher in Machine Learning',
       '18009346 - Mgr/Sr. Mgr - Data Scientist - Customer Data Science',
       'Sr Research Coordinator', 'ANALYST, PROGRAM RESEARCH',
       'Assistant Director - Pharmacy Medication Safety',
       'Clinical Interviewer', 'Adtech Senior Data Scientist',
       'Assistant Vice President - Data Science Business Strategist',
       'Chief Economist', 'Recruiting Coordinator',
       'Associate/Senior Associate, Data Scientist', 'Backend Developer',
       'GIR, Equity Research, Biotechnology, Analyst/Associate - New York',
       'Video Development Editor',
       'Assistant Vice President, Analytics Translation',
       'Population Health Operations Analyst', 'HR Analyst',
       'Carpentry Supervisor', 'Analyst',
       'Associate Director, Data & Analysis (Social Analytics)',
       'Bioinformatician / Postdoctoral Fellow',
       'Quality Control Scientist II',
       'Evaluation Specialist/Foodborne, Bureau of Communicable Diseases',
       'Product Strategist', 'Junior Recruiter', 'Director',
       'Senior Associate, Customer Analytics',
       'Residency/Fellowship Program Coordinator', 'Statistical Analyst',
       'Applied Research Scientist, Computer Vision',
       'Sales Development Representative', 'Big Data Architect',
       'Director, NLP Data Scientist',
       'Senior Data Scientist, Healthcare',
       'Entry-Level Environmental Engineer', 'Senior Data Analyst',
       'MSAT Scientist', 'Mgr-Security',
       'Data Visualization Product Manager',
       'Clin Doc Improvement Qual Analy',
       'AI Engineer - Machine Learning - New York, US', 'UX Researcher V',
       'Quantitative Asset Modeler', 'Analyst - Team IBM Media',
       'Executive Assistant to Chair',
       'Research Assistant (Multiple Positions)',
       'Lead Data Scientist - Aerospace',
       'Business Intelligence Research Analyst', 'Tech Editor',
       'Planning Associate', 'Snr Presales Consultant (FAS)',
       'Research Analyst, Proposals',
       'Senior Data Scientist, Senior Associate',
       'Trading Data Scientist',
       'Secretary II- Langone Orthopedic Center', 'Sub',
       'Data Visualization Software Engineer',
       'Quantitative Research Lead, Quantitative Strategies Group',
       'Client Technical Consultant',
       'Research Associate, Process Sciences and Discovery (New York)',
       'Data Science Associate Director - Advanced Analytics',
       'Data Analyst Co-Response Unit, Office of the Executive Deputy Commissioner',
       'Machine Learning Engineer, Adtech',
       'Senior Machine Learning Scientist', 'Administrative Coordinator',
       'Clin Doc Compliance Specialist (CCS - Inpatienct Coding Experience)',
       'Staff Geologist',
       'Data Scientist - Senior Consultant - New York, NY',
       'Equity Research Analyst - Healthcare', 'Medical Secretary',
       'Analyst - Blockchain, Strategic Advisory Group',
       'Assistant Editor, Mathematics',
       'Data & Pipeline Project Leader, Simons Observatory',
       'Data Governance Manager, Bureau of Epidemiology Services',
       'Senior Research Staff Assistant',
       'Head of Enterprise Data Architecture',
       'Program Planner , Bureau of HIV/AIDS Prevention and Control/HIV/AIDS Care & Treatment',
       'Biostatistician II', 'Director, Senior Lead Data Scientist',
       'Pre Transplant Kidney Coordinator', 'Programmatic Specialist',
       'Senior Software Engineer - Data Visualization',
       'Environmental Health and Safety Specialist I',
       'Quantitative Fixed Income Risk Analyst',
       'Principal Machine Learning Data Scientist - Cloud Platform',
       'Gift Processing Coordinator (Nonprofit)', 'Teaching Assistant',
       'Senior Data Scientist - Healthcare Analytics & Delivery, New Ventures',
       'GIS Analyst', 'Color Scientist',
       'Scheduling Optimization Engineer', 'Scientist I - Orangeburg NY',
       'DATA ARCHITECT', 'Operations Research Analyst',
       'ASSOCIATE SCIENTIST - Microscopy Core and Advanced Bioimaging Center',
       'Senior Associate, Data Scientist (NLP/AI)',
       'Clinical Research Coordinator',
       'Machine Learning Specialist Solutions Architect',
       'Executive Director- Machine Learning & Big Data',
       'Data Scientist (PhD) Data Curation', 'Senior AI Scientist',
       'Quantitative Finance Analyst',
       'Innovation Scientist - Skin Biology', 'Senior Scientist',
       'Senior Research Scientist- Domestic',
       'Senior-Inventive Scientist- Next Gen 5G',
       'Equity Research Analyst (Industrials)',
       'Research Position (Various Levels), Neuroscience',
       'Statistical Programmer/Data Manager - General Medicine',
       'Senior Data Scientist - Predictive Analytics - Time series',
       'Senior Analyst, Data & Analysis (Social Analytics)',
       'Staff Associate', 'Bioinformatics Specialist',
       'Policy Research Analyst',
       'Data Scientist - Healthcare Analytics & Delivery, Advanced Analytics',
       'Lead Data Scientist, Technology - New York, NY or Rockville, MD',
       'Animal Research Technician I',
       'Associate Director, Lead Data Scientist',
       'CCB - Risk-Fraud Data Scientist/Modeler-ML-Pipeline',
       'QUALITY IMPROVEMENT RESEARCH ANALYST - SURGERY',
       'Custom Index Analyst, Quantitative Modeling',
       'Research Position (Various Levels), Numerical Algorithms',
       'Director of Data Analytics', 'DATA ENGINEER',
       'VP of Engineering - NYC', 'Senior Associate, Data Scientist',
       'Financial Services Associate (Inpatient)',
       'Options Trading Analyst', 'Operations System Hacker',
       'Certifying Scientist', 'International Research Analyst',
       'Leveraged Loan Research Analyst',
       'Principal Data Scientist (Media)',
       'Junior Production Coordinator', 'Junior Copywriter',
       'Env Health & Safety Assistant', 'Manager - Data Scientist',
       'VP, Data Science',
       'Machine Learning Data Scientist-Equity Investment Research',
       'Data Scientist-Research Analyst', 'Env Health & Safety Spec I',
       'Data Scientist / Senior Strategic Analyst (Communications & Marketing)',
       'FGP Sec II-Intake/Sched-Radiology', 'Media Research Analyst',
       'Analyst, Quantitative Research',
       'Research Analyst Intern - Blockchain',
       'Policy and Research Analyst Interns - Strategic Policy Unit (3 vacancies)',
       'Assistant Research Coordinator-Interventionist',
       'Statistical Analyst/Data Manager - General Medicine',
       'Senior Applied Scientist - Amazon AI',
       'Research Analyst-Technical', 'Borough Planner',
       'Machine Learning Research Scientist - Text Analytics',
       'Bioinformatics Scientist (Statistical Genetics/Genetic Epidemiology)',
       'Analyst - Trading, Research',
       'Data Manager, Bureau of School Health',
       'Senior Analyst, Data and Analysis',
       'Technical Data Analyst - Marketing', 'Executive Assistant',
       'CVP Data Science - Marketing',
       'Learning and Development Coordinator',
       'JP Morgan Chase Institute- Research Analyst for Financial Markets',
       'Director of Operational Data Science',
       'TradeOps Analyst - New York', 'Scientist I',
       'Sales Operations & Enablement Associate',
       'Quantitative Researcher', 'Community Manager + Editor',
       "FGP Sec II-Intake/Sched- Center for Men's Health",
       'MTC Technical Architect - Data & AI', 'Software Engineer - Data',
       'Histotechnician - IHC', 'Analyst - CoinList Capital',
       'Electronic Trader', 'Epic HIM Analyst',
       'Environmental Compliance Specialist', 'Research Associate',
       'POLICY AND OPERATIONS RESEARCH | ANALYST',
       'Backend Data Engineer', 'Prospect Research Analyst',
       'Lead Data Scientist, Hedge Fund',
       'Sr Business Analyst, Reporting & Data Analysis (Remote New York)',
       'CIB Data Analytics - Machine Learning Program Execution Associate',
       'Biotechnology Research Analyst', 'Director, Data Scientist',
       'BCG Platinion | MAYA Design Human Scientist',
       'AI Research Scientist', 'Office Manager', 'Program Assistant',
       'Senior Data Scientist, Ad-Tech',
       'Data Scientist - Actuarial and Product Analytics',
       'Research Analyst II',

In [9]:
df1['position'] = df1['position'].str.lower() #make all the strings in the position variables in lowercase

In [13]:
df1['position']=df1['position'].str.replace(' ','_', regex=True)

data_scientist = []
data_engineer = []
data_analyst = []


data_scientist = df1[df1['position'].str.contains('data scientist|machine learning|statistician')]

data_scientist

if you match 'data scientist' AND NOT 'data analyst' AND NOT 'data engineer':
    then newpos.append(1)
if you match 'data analyst' AND NOT 'data scientist' AND NOT 'data engineer':
     then newpos.append(2)
if you match 'data engineer' AND NOT 'data scientist' AND NOT 'data analyst':
     then newpos.append(3)
if you match 'machine learning' AND NOT 'data engineer' AND NOT 'data scientist' AND NOT 'data analyst':
     then newpos.append(3)


data_analyst = df1[df1['position'].str.contains('data analyst')]
data_engineer = df1[df1['position'].str.contains('data engineer')]
machine_learning = df1[df1['position'].str.contains('data engineer')]


data_scientist.info()
data_scientist['position'].unique()

data_analyst.info()

In [32]:
data_engineer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31 entries, 187 to 962
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   position     31 non-null     object
 1   company      31 non-null     object
 2   description  31 non-null     object
 3   numreview    21 non-null     object
 4   location     31 non-null     object
dtypes: object(5)
memory usage: 1.5+ KB

In [14]:
df1.loc[df1['position'].str.contains('data_scientist|machine_learning|statistician'), 'data_scientist']=1
df1.loc[df1['position'].str.contains('data_analyst|data_analytics|_analytics|quantitative_analyst'), 'data_analyst']=1
df1.loc[df1['position'].str.contains('data_engineer|data_science_engineer|quantitative_data_engineer'), 'data_engineer']=1

In [15]:
df1

,position,company,description,numreview,location,data_scientist,data_analyst,data_engineer
0,data_scientistâ€”research_(ref_#_exec/rd_dat_nyc...,New York State Office of the Attorney General ...,"<span id=""job_summary"" class=""summary""><p><b>E...",NaN,"New York, NY",1.0,NaN,NaN
1,data_scientist/pre_sales_engineer,Celonis,"<span id=""job_summary"" class=""summary""><p>Celo...",NaN,"New York, NY",1.0,NaN,NaN
2,data_analyst/research_scientist,Columbia University Medical Center,"<span id=""job_summary"" class=""summary""><p>We a...",217 reviews,"New York, NY 10032",NaN,1.0,NaN
3,data_scientist,fractalanalytics,"<span id=""job_summary"" class=""summary""><div><p...",NaN,"Jersey City, NJ",1.0,NaN,NaN
4,data_scientist,Blackboard Insurance,"<span id=""job_summary"" class=""summary""><div><p...",NaN,"New York, NY",1.0,NaN,NaN
...,...,...,...,...,...,...,...,...
981,data_scientist,Scienaptic Systems Inc,"<span id=""job_summary"" class=""summary""><p>Scie...",NaN,"New York, NY",1.0,NaN,NaN
982,junior_data_scientist,Viacom,"<span id=""job_summary"" class=""summary""><div><h...",459 reviews,"New York, NY",1.0,NaN,NaN
983,data_scientist_(entry-level),First Derivatives plc,"<span id=""job_summary"" class=""summary""><p><b>J...",10 reviews,"New York, NY",1.0,NaN,NaN
984,data_scientist,Cityblock Health,"<span id=""job_summary"" class=""summary"">Who we ...",NaN,"Brooklyn, NY 11201",1.0,NaN,NaN
985,junior_data_scientist_apprenticeship,IBM,"<span id=""job_summary"" class=""summary""><div><b...","22,249 reviews","New York, NY 10002",1.0,NaN,NaN

In [21]:
df1['data_scientist']= df1['data_scientist'].fillna(0)
df1['data_analyst']= df1['data_analyst'].fillna(0)
df1['data_engineer']= df1['data_engineer'].fillna(0)
df1

,position,company,description,numreview,location,data_scientist,data_analyst,data_engineer
0,data_scientistâ€”research_(ref_#_exec/rd_dat_nyc...,New York State Office of the Attorney General ...,"<span id=""job_summary"" class=""summary""><p><b>E...",NaN,"New York, NY",1.0,0.0,0.0
1,data_scientist/pre_sales_engineer,Celonis,"<span id=""job_summary"" class=""summary""><p>Celo...",NaN,"New York, NY",1.0,0.0,0.0
2,data_analyst/research_scientist,Columbia University Medical Center,"<span id=""job_summary"" class=""summary""><p>We a...",217 reviews,"New York, NY 10032",0.0,1.0,0.0
3,data_scientist,fractalanalytics,"<span id=""job_summary"" class=""summary""><div><p...",NaN,"Jersey City, NJ",1.0,0.0,0.0
4,data_scientist,Blackboard Insurance,"<span id=""job_summary"" class=""summary""><div><p...",NaN,"New York, NY",1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
981,data_scientist,Scienaptic Systems Inc,"<span id=""job_summary"" class=""summary""><p>Scie...",NaN,"New York, NY",1.0,0.0,0.0
982,junior_data_scientist,Viacom,"<span id=""job_summary"" class=""summary""><div><h...",459 reviews,"New York, NY",1.0,0.0,0.0
983,data_scientist_(entry-level),First Derivatives plc,"<span id=""job_summary"" class=""summary""><p><b>J...",10 reviews,"New York, NY",1.0,0.0,0.0
984,data_scientist,Cityblock Health,"<span id=""job_summary"" class=""summary"">Who we ...",NaN,"Brooklyn, NY 11201",1.0,0.0,0.0
985,junior_data_scientist_apprenticeship,IBM,"<span id=""job_summary"" class=""summary""><div><b...","22,249 reviews","New York, NY 10002",1.0,0.0,0.0

In [22]:
df1.duplicated().sum()

0

In [30]:
df1.to_excel(r'df1_NY.xlsx', index=False)

ModuleNotFoundError: No module named 'openpyxl'